INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'banana', 'tropical', '1');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'banana', 'tropical', '2');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'pepper', 'tropical', '3');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'pepper', 'tropical', '4');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'black pepper', 'tropical', '5');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'black pepper', 'tropical', '6');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'lettuce', 'tropical', '7');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'lettuce', 'tropical', '8');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'lime', 'tropical', '9');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'lime', 'tropical', '10');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'pineapple', 'tropical', '11');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'pineapple', 'tropical', '12');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'sea weed', 'tropical', '13');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'grape', 'tropical', '14');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'mikan', 'tropical', '15');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'green algae', 'tropical', '16');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'seaking scales', 'tropical', '17');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'paprika', 'tropical', '18');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'salt', 'tropical', '19');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'suggar', 'tropical', '20');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'apple', 'mediterranean', '1');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'apple', 'mediterranean', '2');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'tomato', 'mediterranean', '3');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'tomato', 'mediterranean', '4');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'rice', 'mediterranean', '5');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'rice', 'mediterranean', '6');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'beans', 'mediterranean', '7');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'beans', 'mediterranean', '8');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'cinammon', 'mediterranean', '9');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'cinammon', 'mediterranean', '10');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'bay leaves', 'mediterranean', '11');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'bay leaves', 'mediterranean', '12');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'garlic', 'mediterranean', '13');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'carrot', 'mediterranean', '14');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'oregano', 'mediterranean', '15');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'grounded nuts', 'mediterranean', '16');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'corn', 'mediterranean', '17');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'mushroom', 'mediterranean', '18');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'nuts', 'mediterranean', '19');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'mikan', 'mediterranean', '20');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'ginger', 'temperate', '1');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'ginger', 'temperate', '2');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'lettuce', 'temperate', '3');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'lettuce', 'temperate', '4');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'flour', 'temperate', '5');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'flour', 'temperate', '6');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'pumpkin', 'temperate', '7');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'pumpkin', 'temperate', '8');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'radish', 'temperate', '9');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'radish', 'temperate', '10');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'yam', 'temperate', '11');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'yam', 'temperate', '12');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'salt', 'temperate', '13');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'pumpkin pie spice', 'temperate', '14');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'bay leafs', 'temperate', '15');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'mushroom', 'temperate', '16');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'rice', 'temperate', '17');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'beans', 'temperate', '18');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'nuts', 'temperate', '19');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'grounded nuts', 'temperate', '20');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'carrots', 'special', '1');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'carrots', 'special', '2');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'potato', 'special', '3');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'potato', 'special', '4');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'mushroom', 'special', '5');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'mushroom', 'special', '6');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'nuts', 'special', '7');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'nuts', 'special', '8');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'tomato', 'special', '9');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'tomato', 'special', '10');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'banana', 'special', '11');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'banana', 'special', '12');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'garlic', 'special', '13');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'cinnamon', 'special', '14');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'ginger', 'special', '15');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'radish', 'special', '16');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'yam', 'special', '17');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'black pepper', 'special', '18');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'grape', 'special', '19');
INSERT INTO jobitems (idJob, itemName, climate, itemDices) VALUES ('1', 'corn', 'special', '20');
